zendframework/zend-diactoros

README.md

I'm expert of README.md file :)
ping @Ocramius

in-line representation

---

.travis.yml

composer self-update is not required
composer install arguments are not required too

[travis-ci] Clean composer install commands

---

README.md

Enhancement: Add link to GitHub repository

---

README.md

Per the question on #27.
Thanks, @ezimuel !

[#27] Added phonetic pronunciation to README

---

src/RequestTrait.php

Fix: Remove unused import

---

.travis.yml

* [travis-ci] Optimize composer install having all requirements set
Avoid to execute the requirements resolution algorithm twice
* [travis-ci] Ensure composer install is always done
Retry the operation if a network split occur and ignore system requirements for avoid errors if a required extension is disabled
* [travis-ci] Execute CS test with PHP 5.5
Static analysis performs better when xdebug is turned off
Before: 4.5s -  After: 1.7s
* [travis-ci] Enable cache
Composer is updated for to prevent cache invalidation due stat operations over cached files

[travis-ci] Various optimizations

---

doc/book/custom-responses.md

Typo fixed

---

.travis.yml

Per comment from @Maks3w on #73, this adds an `install` script to print the
installed dependencies.

Print installed dependencies

---

.gitattributes

Some files were not necessary. Especially changelog.md that can grow fast

Add files to .gitattributes

---

src/Response/SapiEmitter.php
src/Response/SapiEmitterTrait.php

According with #107 I've moved the common functions of SapiEmitter to a trait in order to create a new SapiStreamEmitter in other pull request.

Created SapiEmitterTrait

---

src/Response/SapiEmitter.php
src/Response/SapiEmitterTrait.php
src/Response/SapiStreamEmitter.php
test/Response/SapiStreamEmitterTest.php

According with #107, here's the emitter for big streams. There's also an implementation of `Content-Range` header to return only a specific range of the stream (useful for video and audio, for example).

Added the SapiStreamEmitter

---

test/Response/SerializerTest.php

Unit test which shows an issue

Issue with status code on response deserialization

---

.travis.yml
composer.json

Handy scripts for triggering PHPUnit, coveralls, etc. from composer. Same as on `zend-expressive`.

Composer scripts

---

src/PhpInputStream.php

Same value is as default in parent class.

Remove unused constructor param

---

src/UploadedFile.php

I was going through the class and thought it might help others to have the doc bloc added.

Add constructor doc bloc for UploadedFile

---

src/Uri.php
test/UriTest.php

Fixes #93 : withFragment() deviates from PSR-7

---

src/ServerRequestFactory.php
test/ServerRequestFactoryTest.php

This is still failing on version 1.3.4 even though it should have been fixed with #117?

Accept HTTP/2 protocol

---

src/ServerRequestFactory.php
test/ServerRequestFactoryTest.php

As proposed in #164.
I hope sending this to master is correct!?

Parse headers from REDIRECT_* env vars

---

src/Request.php
src/ServerRequest.php

It is supported by `$this-> initialize()`

Allow for UriInterface

---

CONTRIBUTING.md
composer.json
composer.lock
phpcs.xml
src/Uri.php
test/RequestTest.php
test/ResponseTest.php
test/StreamTest.php

Usage of the newly introduced zendframework/zend-coding-standard for CS checks.

New coding standard

---

src/Response/SapiStreamEmitter.php
test/Response/SapiStreamEmitterTest.php

SapiStreamEmitter only sends subsets if the unit is bytes

---

composer.json

All other PSR implementations seem to follow this format.

Update the provide section in composer.json

---

.travis.yml
test/Response/JsonResponseTest.php

in favor of @weierophinney comment at https://github.com/zendframework/zend-diactoros/pull/259#issuecomment-315531571

remove hhvm support

---

.travis.yml

- Removes env and script items targetting documentation builds
- Removes notifications for IRC and Slack
- Removes distribution locking (no longer needed, as we are no longer building for HHVM)

Updates Travis configuration

---

src/Response.php

https://datatracker.ietf.org/doc/draft-ietf-httpbis-early-hints/

Add early hint status code

---

src/ServerRequestFactory.php
test/ServerRequestFactoryTest.php

Unknown variable **$name**. This should be the **$header**.

Corrected reference to undefined variable in `ServerRequestFactory#getHeader()`

---

src/AbstractSerializer.php

There was duplicated strict type declaration in that file.

Removed duplicated strict type declaration

---

LICENSE.md

Welcome to the future

---

.travis.yml

Hotfix: Travis CI configuration - upload coverage report to coveralls
