src/ServerRequest.php
test/ServerRequestTest.php

When using `getAttribute` before `withAttribute` has been called the following error happens:
`array_key_exists() expects parameter 2 to be array, null given`
This fix makes sure the array is initialized in the `ServerRequest` class. I'm open to other suggestions for solving this issue.
cc: @weierophinney

Fix error when accessing a single attribute before any have been added.

---

src/RequestTrait.php

Fix: Enviornment is spelled m-o-o-n

---

src/ServerRequest.php
test/ServerRequestTest.php

I am using the symfony psr bridge currently, and there are a few problems because of missing default values in ServerRequest:
```php
/**
* @var array
*/
private $cookieParams;
/**
* @var array
*/
private $parsedBody;
/**
* @var array
*/
private $queryParams;
/**
* @var array
*/
private $serverParams;
/**
* @var array
*/
private $uploadedFiles;
```
I can see in the construtor, that `$serverParams` and `$uploadedFiles` will be initialized. The `$attributes` have ben fixed here: https://github.com/zendframework/zend-diactoros/pull/9
But why are `$cookieParams`, `$parsedBody` and `$queryParams` by default NULL and not a empty array? This is not compatile with the api of ServerRequestInterface.

Default values in ServerRequest

---

.travis.yml
composer.json
phpcs.xml
src/HeaderSecurity.php
src/RequestTrait.php
src/Response.php
src/ServerRequestFactory.php
src/Stream.php
src/UploadedFile.php
test/HeaderSecurityTest.php
test/RequestTest.php
test/TestAsset/Functions.php

Supersede and close https://github.com/zendframework/zend-diactoros/pull/28/

[cs] Place CS rules in config file

---

README.md

Fix: Diactoros has actually just one dependency

---

src/Request.php

Fix: Add missing import

---

src/HeaderSecurity.php
test/HeaderSecurityTest.php

Replacing `for` loop with regular expressions brought visible performance improvement to header validation.
See simple benchmark: https://gist.github.com/mtymek/660b388db0c5b9d63bc0

improve header validation speed

---

src/RequestTrait.php

This PR
:bulb: Not sure if this is right - is it?

Fix: Add property annotations to class-level docblock

---

.travis.yml
composer.json
test/RelativeStreamTest.php
test/Request/SerializerTest.php

Drupal 8 has a minimum PHP of 5.4.8. Symfony 2.7 still depends on 5.3.something. 5.4 is a reasonable middle-ground to ensure that new libraries targeting older versions of PHP do not need to be written.
This will be a temporary change; we will likely update the minimum required version in one of the next few minor releases.

Drop minimum required PHP version to 5.4

---

src/MessageTrait.php
src/RequestTrait.php

This PR
:question: Seems to make more sense to me, how about you?

Fix: Return static instead of self

---

src/Response/EmptyResponse.php
src/Response/StringResponse.php
test/Response/EmptyResponseTest.php
test/Response/StringResponseTest.php

`StringResponse::blank(401)`, as that's another common use case (though now `StringResponse` may not be perfect).
It's called `blank()` because `empty()` cannot be used as method name until PHP 7. Any better ideas?

Add shortcut method for empty responses

---

src/UploadedFile.php
test/UploadedFileTest.php

Hi,
I found the UploadedFile class throws an exception,
```php
InvalidArgumentException('Invalid stream or file provided for UploadedFile');
```
when no file is selected for upload.
This is indeed an error, with UPLOAD_ERR_NO_FILE. But I thought it would be nice if no exceptions are thrown at the creation of server request.

file upload without file selected throws an exception

---

src/RequestTrait.php
test/RequestTest.php

It will be nice feature to define own custom http method. Now it's not possible to override or add new one. I can provide PR, but I want to know what are you think about it.

Custom HTTP method

---

doc/book/custom-responses.md
src/Response/RedirectResponse.php
test/Response/RedirectResponseTest.php

Besides the HTML and JSON responses introduced in #52 and the empty response implemented in #58, the other most common server-side response type is a redirect. This pull request implements a `RedirectResponse`, which accepts a URI in order to produce a 302 response with a `Location` header. As per the other response types, this custom response type allow specifying an alternate status code and headers to use at initialization.
Examples as documented:
```php
// 302 redirect:
$response = new RedirectResponse('/user/login');
// 301 redirect:
$response = new RedirectResponse('/user/login', 301);
// using a URI instance (e.g., by altering the request URI instance)
$uri = $request->getUri();
$response = new RedirectResponse($uri->withPath('/login'));
```

Implement RedirectResponse

---

phpunit.xml.dist
src/Response/HtmlResponse.php
src/Response/JsonResponse.php
test/Response/HtmlResponseTest.php
test/Response/JsonResponseTest.php

I would like to suggest splitting the new `StringResponse` into 2 smaller classes: `JsonResponse` and `HtmlResponse`.
Here is the rationale:
`StringResponse` is actually a `StringResponseFactory`. It is final, so it cannot be extended, and it provides only 2 static methods: `html` and `json`. However, there are a bunch of other perfectly viable responses that are also "strings". For instance, why is there no `xml` method? As time goes by, it is likely that this class will start growing and growing up to the point where it is not maintainable anymore.
Also, yesterday, I tried to implement my own response. I ended up copy-pasting the `createResponse` method in my own class. I think this method is very valuable and should be exposed.
Would you be ok if I submit a pull request splitting …

Splitting StringResponse into many smaller classes

---

doc/book/custom-responses.md
src/Response/JsonResponse.php
test/Response/JsonResponseTest.php

As noted on #63, casting nulls and scalars to objects and arrays, respectively, is not necessary, and likely unwanted; it could even be considered buggy behavior.
This patch eliminates the casting entirely, and updates the tests to ensure that scalars are encoded verbatim.

Remove casting prior to JSON serialization

---

src/Stream.php
test/StreamTest.php

Problem:
Stream accept resource, not only stream resource.
You can initialize stream class with wrong parameter.
Simple(bad) test:
```php
public function testCanNotInstantiateWithStreamIdentifier()
{
$true = false;
$image = imagecreate(200, 200);
try {
$this->stream = new Stream($image, 'wb+');
} catch(\Exception $e)
{
$true = true;
}
$this->assertTrue($true); //test is red
}
```
Simple (not that bad) solution.
```php
if (is_resource($stream)) {
$type = get_resource_type($stream);
if($type !== 'stream')
{
throw new \InvalidArgumentException("Resource is not a stream");
}
$this->resource = $stream;
} elseif (is_string($stream)) {
```

Stream class accept all resource types

---

.travis.yml
CHANGELOG.md

- Per http://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/
Mainly testing this out. :)

Added vendor to travis cache

---

.travis.yml

Builds have been erroring due to hitting GitHub API rate limits.

Prefer source, to prevent github API rate limits

---

src/UploadedFile.php
test/UploadedFileTest.php

Updates `writeFile()` to call `getStream()` instead of assuming `$stream` is already populated correctly; this ensures that if a filename, and not a stream or resource, was provided to the constructor, the file can still be correctly moved.
Fixes #82

[#82] Ensure `moveTo()` works in non-SAPI environments

---

src/Response/SapiEmitter.php
test/Response/SapiEmitterTest.php
test/ServerTest.php

Fixes #84
One test is failing because of a side-effect in unrelated tests. Need to work on it, but if you have an idea on the best way to fix it's welcome, I'm not familiar with everything yet.

Set the Content-Length header when emitting the response

---

src/Uri.php
test/UriTest.php

withPort should allow null port

Fix to make withPort fully compliant with PSR-7

---

CHANGELOG.md
src/Response/JsonResponse.php
test/Response/JsonResponseTest.php

Updated the default `$encodingOptions` to also include `JSON_UNESCAPED_SLASHES`, which is a sane default, and still complies with RFC 4627 (forward slash, or the solidus, does not need to be escaped).

Use unescaped slashes in encoded JSON by default

---

CHANGELOG.md
src/RequestTrait.php
test/RequestTest.php

`RequestTrait::withUri` method [uses non-lowercased name for header "Host"](https://github.com/zendframework/zend-diactoros/blob/1.1.3/src/RequestTrait.php#L251). This can lead to duplicate "Host" header in request:
```php
$request = new \Zend\Diactoros\Request();
$request = $request->withHeader('host', 'foo.com');
// ...
$request = $request->withUri(new \Zend\Diactoros\Uri('http://bar.com'));
print_r($request->getHeaders());
```
Output:
```
Array
(
[host] => Array
(
[0] => foo.com
)
[Host] => Array
(
[0] => bar.com
)
)
```
And raw HTTP request will be something like this:
```
GET / HTTP/1.0
Host: foo.com
...
Host: bar.com
```

Duplicate "Host" header when using "RequestTrait::withUri" method

---

src/CallbackStream.php
test/CallbackStreamTest.php

Hello.
This is a implementation of Stream that uses a callback as described in #70 
Maybe should be great to add support for generators, to allow doing thinks like this:
```php
$stream = new CallbackStream(function () {
$command = new Command();
$command->run();
while ($command->isRunning()) {
yield $command->getOutput(); //returns always a string
}
return false; //end of the command
});
```
In this case, the emitter should iterate with the stream, instead return all content at once. I mean:
```php
while (!$stream->eof()) {
echo $stream->read(1);
};
```
This behaviour is not implemented (currently `$stream->read()` throws a `RuntimeException` and the callback can be executed only once), but I can do it if you like.

added CallbackStream

---

src/MessageTrait.php
test/MessageTraitTest.php

Pull request to fix Issue #100

Fixing issue #100 withHeader does not remove old header value

---

src/Response.php
test/ResponseTest.php

I decided to simplify set status code. Why? Constructor's phpdocs says that it's expected `$status` variable as int, not null, only int. I know that make BC, however it should be done in my opinion

Simplify status code

---

src/MessageTrait.php
test/MessageTraitTest.php
test/RequestTest.php
test/ResponseTest.php

I have tried to create a request and I added header:
```php
[
'X-User-Id': 123,
]
```
After this my request doesn't have `X-User-Id` header. After debug I have found this https://github.com/zendframework/zend-diactoros/blob/1037ed1cb4e240eba665597e4c373e57fb9ea24c/src/MessageTrait.php#L341
Should we throw exception instead of continue code execution?

Header value not string

---

src/ServerRequestFactory.php
test/ServerRequestFactoryTest.php

Parse protocol version

---

src/ServerRequestFactory.php
test/ServerRequestFactoryTest.php

> Cookies *are* available in $_COOKIE, and hence also the cookie params, but there may be times you want raw access to the header. There's no good reason to omit the header from the request.
> – @weierophinney
I've been working with [dflydev/fig-cookies](https://github.com/dflydev/dflydev-fig-cookies) which relies entirely on being able to read and parse the cookie header from `RequestInterface` instances. Much to my surprise, request instances didn't have a cookie header even though I was sending cookies.
After a quick chat with @weierophinney he was able to verify that cookie headers were indeed intentionally being excluded as a header for `ServerRequestInterface` instances that were created using the `ServerRequestFactory`.
This PR allows cookie headers that are sent to be included in …

Include COOKIE header in request headers

---

src/Response.php

https://datatracker.ietf.org/doc/draft-ietf-httpbis-legally-restricted-status/?include_text=1
The HTTP 451 status code was approved by the ISG a few days ago on the 18th December '15.

Added HTTP 451 status code

---

CONTRIBUTING.md

I found a minor typo in the contributing guide wrt the diactoros repository.

Fix minor typo in contributing guide

---

src/HeaderSecurity.php

With current version of Diactoros I often see exceptions like "Invalid header value". It doesn't show which header is not valid, making it difficult to see what's the problem. 
With this PR server logs will clearly show which header caused exception.

Verbose exception message from header validators

---

src/Response/SapiStreamEmitter.php
test/Response/SapiStreamEmitterTest.php

Make `SapiStreamEmitter` work with streams that don't support seek operations. This allows `CallbackStream` responses to be combined with `SapiStreamEmitter`.
Refs #199

Fix incompatibilities between Unseekable streams and SapiStreamEmitter

---

src/Uri.php
test/UriTest.php

Currently, we can't work with non-latin letters in path. For example: http://example.com/тестовый_путь/ or http://example.com/flüg/. I resolve this problem by adding in `CHAR_UNRESERVED ` constant `\pL` for support utf-8 letters.

Added support for utf8 path

---

src/Response/Serializer.php
test/Response/SerializerTest.php

The newline after the headers was missing if the response body was empty.

Fix reponse serialization if response body is empty.

---

src/RequestTrait.php
test/RequestTest.php

psr-7 attempt to set the Host header during construction

---

src/UploadedFile.php

- test for already moved file 1st (or 2nd) : testing a boolean can avoid heavier tests
- unify string and empty string in a single test: the exception message suggests both requirements

moveTo: check targetDirectory and more

---

src/ServerRequestFactory.php

at the end HTTP_ and CONTENT_ header names from $_SERVER and mocked request are normalized to lowercase, so nice formatting function calls (ucwords/ucfirst) are redundant.

remove overwritten function calls

---

src/Uri.php
test/UriTest.php

Alternate fixes #192

---

src/Response/SapiStreamEmitter.php

Used relative stream to simplify emitBodyRange. Removes necessity to check lower bound

---

src/Request.php

Fix undefined class UriInterface in PHPDoc

---

src/Response.php

At https://github.com/cakephp/cakephp/issues/9516, we were discussing missing status codes in CakePHP's and Zend's libraries.
This brings both (almost) [in sync](https://github.com/cakephp/cakephp/pull/9523) by adding missing status codes & messages.
Used https://httpstatuses.com/ as reference.

Add missing HTTP status codes/messages

---

src/Uri.php
test/UriTest.php

https://github.com/zendframework/zend-diactoros/pull/159 adds support for UTF-8 in host, and https://github.com/zendframework/zend-diactoros/pull/166 for path, but the query string still lacks UTF-8 support.

Add support for UTF-8 query string

---

src/Response/SapiStreamEmitter.php
test/Response/SapiStreamEmitterTest.php

@Ocramius 
I tried to improve some points in the SapiStreamEmitter tests:
- Reduced code repetition by creating a new method for the Stream Prophecy common code.
- Added a method for expanding the test data set. This facilitates the addition of new data set with one information changed (e.g.: the contents).
- Improved checks of methods that can or cannot be called.
- Removed  the expectation of read counts because the buffer size is the maximum, the implementation can use a smaller one if you want.
- Considering bug #225, which I was not able to reproduce, both in the test and in an Expressive application. Added new tests for each type of response, checking what was emitted, and whether the content type was not changed.
Just a few comments:
- I didn't add out of range conditions to the …

Improves SapiStreamEmitter tests, preventing unnecessary string casts

---

src/Response.php

uses uppercase for "used", changed to "Used"

Fixes typo IM Used response reason phrase typo

---

.travis.yml
composer.json
composer.lock
src/UploadedFile.php
test/UploadedFileTest.php

This will save people some time figuring out why the upload isn't working.
Can't think of any tests.

Pass the SAPI file upload errors when throwing an exception

---

.travis.yml
src/RelativeStream.php
src/Stream.php
test/RelativeStreamTest.php
test/StreamTest.php

I have noticed this with amazon S3 it does return resource with meta `seekable => false` and I can't use this I have to create file and the n create new stream from it. Also does not make sense to rewind not seekable stream.

__toString() always return empty content when resource is not seekable

---

src/Response/SapiEmitterTrait.php

When using native PHP sessions with cookies, PHP will set a cookie whenever a session is created or regenerated. Adding an additional `Set-Cookie` header in the same request will cause the PHP `Set-Cookie` header to be lost. Ideally native PHP sessions with cookies should be avoided when using PSR-7 compatible classes, but that is not always possible - this PR makes sure PHP's session cookies are not lost.

PHP session cookies are no longer broken

---

src/PhpInputStream.php
test/PhpInputStreamTest.php

Psr-7 StreamInterface::read() returns only string, so don't need check it is empty-like value
fix #255

fix #255 - Don't evaluate '0' as empty

---

src/Uri.php
test/UriTest.php

like in zend-uri issue https://github.com/zendframework/zend-uri/issues/13 with zend-uri PR https://github.com/zendframework/zend-uri/pull/17

reserved characters in path should be unencoded

---

src/Uri.php
test/UriTest.php

According to <https://www.ietf.org/rfc/rfc3986.txt> 3.2.1, the user info parts should actually be URL encoded.

Encode user info when calling withUserInfo()

---

CHANGELOG.md
src/Response/JsonResponse.php
test/Response/JsonResponseTest.php

This PR adds new API to `Zend\Diactoros\Response\JsonResponse`:
`withPayload($data)`
`getPayload()`
`withEncodingOptions($options)`
`getEncodingOptions()`
The constructor now holds a copy of the payload and its encoding options to let consumer modify the final content without having to get the body content, decode it, update it, and then re-invoke the full constructor.
The main use case that inspired this new functionality is adding metadata to a JSON down a middleware pipe, e.g. hypermedia links.
While the native PHP JSON parser is fast enough for simple use cases, this can become a problem with high loads and big JSONs; besides, what consumers must resolve to do is arguably in-elegant; here is an example of a middleware that adds a `self` link to a JSON response:
```php
$response = …
```

JsonResponse additional API

---

.travis.yml

Removed double test coverage run - run it once only on PHP 7.
Simplified condition to remove xdebug when not running tests with coverage.

Hotfix - Travis CI configuration - removed double coverage run

---

src/Response/SapiEmitter.php
src/Response/SapiEmitterTrait.php
src/Response/SapiStreamEmitter.php
test/Response/AbstractEmitterTest.php
test/Response/SapiStreamEmitterTest.php
test/ServerTest.php
test/TestAsset/Functions.php
test/TestAsset/SapiResponse.php

This basically ensures that `zend-diactoros` sends the status code to `header()` while emitting the response headers, preventing PHP from overriding it silently.
IMO this is a bug fix, since the emitted response is different from the created response.
We have a similar solution in `symfony/http-foundation`: https://github.com/symfony/http-foundation/blob/dd97248b62153457d0716738d0dbcc0c2b31e285/Response.php#L331-L338
More info:
- https://bugs.php.net/bug.php?id=70273
- https://bugs.php.net/bug.php?id=51749
- https://bugs.php.net/bug.php?id=74535

Respect response's status code

---

src/MessageTrait.php
src/Uri.php

The old version would be parsed as `($port !== null && $port < 1) || ...`
(That'd have the same results for `null` and `0`,
but is less readable)

Nits on range check for port number, unnecessary sprintf

---

.travis.yml
composer.json

Coverage reporting is only used on a single target, and is only installed conditionally via Travis, so we should not have scripts for uploading coverage within our `composer.json`.

Do not include coverage uploading in composer.json

---

src/Stream.php
test/StreamTest.php

`fstat` calls may return `false` (remote resources, `'php://input'` streams)

check fstat result

---

src/ServerRequestFactory.php

`$scheme` is never empty as it was initialized to `'http'`

remove superfluous $scheme empty test

---

CHANGELOG.md
doc/book/api.md
doc/book/emitting-responses.md
doc/book/overview.md
doc/book/usage.md
src/Response/EmitterInterface.php
src/Response/SapiEmitter.php
src/Response/SapiEmitterTrait.php
src/Response/SapiStreamEmitter.php
src/Server.php

Per #295, these classes have equivalents or 1:1 mappings via the package zendframework/zend-httphandlerrunner. As such, they are deprecated for the 1.8.0 release, to be removed in version 2.0.

Deprecate emitters and the Server class

---

CHANGELOG.md
src/ServerRequestFactory.php
test/ServerRequestFactoryTest.php

Following on #307, this patch removes functionality deprecated for the 1.8 release within `ServerRequestFactory`. This includes all private methods, but also the following public methods:
- `normalizeServer()`
- `marshalHeaders()`
- `marshalUriFromServer()`
- `marshalRequestUri()`
- `marshalHostAndPortFromHeaders()`
- `stripQuerySTring()`
- `normalizeFiles()`

Removes deprecated functionality from ServerRequestFactory

---

CHANGELOG.md
src/Response.php

The IANA HTTP status codes list was updated on 2018-07-02 to reflect a new IETF draft, draft-ietf-httpbis-replay-04, which details a header that may be used to indicate that an "early data" request may not yet be accepted, as no TLS handshake has been previously made, and that the request myust be retried after receiving the 425 response.
Without this change, tests fail on all platforms as the hard-coded reason phrase in `Zend\Diactoros\Response` references an early, non-standards-track usage of the status code.

Updates reason phrase for 425 response status code

---

CHANGELOG.md
src/functions/normalize_uploaded_files.php
test/functions/NormalizeUploadedFilesTest.php

To address https://github.com/zendframework/zend-diactoros/issues/311 (Some/All?) SAPI's index the `tmp_name` etc common fields from the point that a numerically indexed array is encountered which is causing Diactoros to fail fatally with form uploads that use multi-dimensional named fields containing a numeric index (as well as not converting all leaf nodes for deeper hierarchies of file upload field names).
This change updates normalizeUploadedFiles to be recursive and introduces several tests to verify the behaviour matches the PSR-7 spec + the scenario not mentioned by the spec.
Note: given the number of "private" functions being encapsulated in this larger function it may be worth considering converting this to an object instead especially as the recursion and lack of hoisting makes …

#311 - Update NormalizeUploadedFiles to handle multi-dimension recursively

---

src/Stream.php

| Q             | A
| ------------- | ---
| Branch?       | master
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
This PR fixes #298 by removing the usage of the second argument of the `set_error_handler` function and moves the check of the level of the raised error inside the error handler callback.

Workaround PHP bug #63206 in Stream::setStream method

---

CHANGELOG.md
src/functions/marshal_uri_from_sapi.php
test/ServerRequestFactoryTest.php

- Checks for either `HTTPS` or `https` in the `$server` array.
- Does a case-insensitive check against the value discovered to see if it is equivalent to "off".
- Does a case-insenstivie check against the value of the `X-Forwarded-Proto` header to see if it is equivalent to "https".
Fixes #317

Ensure checks for HTTPS scheme are case insensitive

---

.travis.yml
CHANGELOG.md
composer.json
composer.lock
phpunit.xml.dist
src/MessageTrait.php
src/ServerRequest.php
src/Uri.php
test/Integration/RequestTest.php
test/Integration/ResponseTest.php
test/Integration/ServerRequestTest.php
test/Integration/StreamTest.php
test/Integration/UploadedFileTest.php
test/Integration/UriTest.php
test/MessageTraitTest.php

I noticed that this library does not fully comply with psr7. 
I’ve added integration test to show where it is failing. 
(I’m at the airport atm, will complete this PR later)

Add integration tests

---

.gitignore
.travis.yml
CHANGELOG.md
composer.json
composer.lock
doc/book/factories.md
mkdocs.yml
phpunit.xml.dist
src/RequestFactory.php
src/ResponseFactory.php
src/ServerRequestFactory.php
src/StreamFactory.php
src/UploadedFileFactory.php
src/UriFactory.php
test/Integration/RequestTest.php
test/Integration/ResponseTest.php
test/Integration/ServerRequestTest.php
test/Integration/StreamTest.php
test/Integration/UploadedFileTest.php
test/Integration/UriTest.php
test/ServerRequestFactoryTest.php

This patch implements the PSR-17 interfaces, and tests them against the http-interop/http-factory-tests integration test suite.
As part of the change, we are also able to remove the additional integration test dependency when testing against the PSR-7 integration tests. Those tests rely on PSR-17 factories, which we now provide, and map within the `phpunit.xml.dist` file. As such, both PSR-7 and PSR-17 integration tests will run for every build target.
All PSR-17 implementations are alongside the PSR-7 classes they create.
Also adds php nightly build to matrix, to ensure we are prepared for PHP 7.3.

Implement PSR-17

---

src/ServerRequestFactory.php
test/Integration/ServerRequestFactoryTest.php
test/ServerRequestFactoryTest.php

This fixes the `ServerRequestFactory` that always creates a server request with `php://input` as the body stream.

Fixed serverRequest factory

---

.gitattributes

Not sure how this fits the PR template, so I left it out.
I noticed some files in the downloaded package from packagist that should not be there.
Result should be
```
src/
CHANGELOG.md
LICENSE.md
README.md
composer.json
```
Proposed contents are based on other zend projects like
https://github.com/zendframework/zend-httphandlerrunner/blob/master/.gitattributes
https://github.com/zendframework/zend-expressive/blob/master/.gitattributes

Updated export-ignores to cleanup release

---

mkdocs.yml

* copyright notice is no longer needed, because the template already contains this information
* the site description is synchronised with the documentation overview
* the name for the entry page is needed to eliminate the [first wrong / duplicate entry](https://github.com/zendframework/zf-mkdoc-theme/issues/48)

Updates configuration for MkDocs

---

src/functions/marshal_headers_from_sapi.php
test/ServerRequestFactoryTest.php

Bugfix: Header with value "0" is being discarded

---

src/functions/marshal_headers_from_sapi.php
test/ServerRequestFactoryTest.php

Provide a narrative description of what you are trying to accomplish:
```
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'http://xxx.xxx.xxx');
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "PATCH");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, ["Upload-Offset: 0"]);
curl_exec($ch);
```
The header `Upload-Offset` is being stripped. (Any header with value "0")
The value was being used in a conditional.  To test `!!("0") === false`.
Test was incorrect because the header was being stripped because it was not prefixed with `HTTP_`.
Relates to #347 #342 #344 
Values with a string of "0" should be accepted
Test passes with proper header formation.

Headers with value 0 being stripped out. Previous bugfix caused all headers to be accepted.

---

src/UploadedFile.php

When calling `moveTo()` on `UploadedFile` in a `phpdbg` environment, `move_uplaoded_file()` is incorrectly called (and as expected fails). This adds `phpdbg` as a valid "non-SAPI" environment (Same as `cli`)

PHPDBG is also a valid non-sapi environment

---

CHANGELOG.md
src/functions/marshal_uri_from_sapi.php
test/functions/MarshalUriFromSapiTest.php

This modifies the detection of HTTPS by checking whether the lower-case value of the HTTPS-key of the server variable equals 'on'. Before that checked whether the value did *not* match 'off' which meant that the nginx-default for non-HTTPS connections (which, according to the [documentation](http://nginx.org/en/docs/http/ngx_http_core_module.html#var_https) is an empty string) did in fact match and returned that the connection *is* encrypted.
This fixes #362
Provide a narrative description of what you are trying to accomplish: See #362

Modify detection of HTTPS

---

CHANGELOG.md
src/functions/marshal_uri_from_sapi.php
test/ServerRequestFactoryTest.php
test/functions/MarshalUriFromSapiTest.php

As zend-diactoros v1 is still LTS we should provide the hotfix also in that branch.
I've ported @heiglandreas commits with changes to work on v1.
/cc @heiglandreas @weierophinney

Apply #363 (detection of HTTPS) on v1 (LTS)

---

.gitignore
.travis.yml
composer.json
composer.lock
phpunit.xml.dist
test/ResponseTest.php

Refactored iana status codes test provider to use locally cached file instead of downloading them on each tests run.
Also fixed failing tests, replaces #366

Refactor fetching iana http status codes to use caching

---

CHANGELOG.md
src/functions/marshal_headers_from_sapi.php
test/functions/MarshalHeadersFromSapiTest.php

- integer keys should be ignored
- _ should be changed to - in key (also for CONTENT_* headers)
Fixes #369

Hotfix: marshalHeadersFromSapi function

---

src/Uri.php
test/UriTest.php

Fix #357 - invalid characters in path/query

---

src/functions/marshal_uri_from_sapi.php
test/functions/MarshalUriFromSapiTest.php

Hey guys,
we are using NGINX+ with loadbalancing to multiple servers which are not aware of external domain names (for reasons).
However, NGINX provides `X-Forwarded-Host` header to those upstream servers to tell them which external domain was called.
I've added an example on what I would like to expect (even tho that `X-Forwarded-Proto` is being handled for the `https` scheme).
Tell me what you think.

`X-Forwarded-Host` for `marshalUriFromSapi`

---

CHANGELOG.md
docs/book/v2/api.md
src/UploadedFile.php
test/UploadedFileTest.php

This is a new feature to make UploadedFile extend SplFileInfo which enables you to pass UploadedFile instances in places where SplFileInfo typehints are required and use SplFileInfo based methods to access information about the file while still having access to the additional UploadedFile interface.
This is primarily useful for populating models/entities directly from requests wherein a supplied value needs to be an instance of SplFileInfo and wherein a service or hook later may move the files into more appropriate places at time of persistence.

Make UploadedFile Extend SplFileInfo

---

docs/book/v2/api.md
src/UploadedFile.php
test/UploadedFileTest.php

Post-release of 2.2.0, users discovered problems with `UploadedFile` extending `SplFileInfo`, particularly when a stream path is used to create the instance. Additionally, there are some differences with how `UploadedFileInterface` and `SplFileInfo` each define the return type for `getSize()`; the former allows nullification, while the latter does not, but allows raising an exception (something explicitly disallowed in PSR-7).
This patch reverts the code and documentation changes associated with the patch.

Reverts extension of SplFileInfo

---

composer.json
composer.lock
test/MessageTraitTest.php
test/PhpInputStreamTest.php
test/RequestTest.php
test/ResponseTest.php
test/ServerRequestTest.php
test/StreamTest.php
test/UploadedFileTest.php

We cannot use yet PHPUnit 8 as `php-http/psr7-integration-tests` is not compatible with PHPUnit 8.

QA: update PHPUnit and tests
